spring.application.name=proj
spring.datasource.url=jdbc:postgresql://localhost:5432/dev
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true
